ehealth/ehealth/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings

#NOTE!!!! INSTALL DJANGO-REGISTRATION-REDUX v 1.2!!!! otherwise there is an error with get_success_url()

from registration.backends.simple.views import RegistrationView

# Create a new class that redirects the user to the index page, if successful at logging
class MyRegistrationView(RegistrationView):
    def get_success_url(self,request,user):
        return '/ehealth_app/'

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^ehealth_app/', include('ehealth_app.urls')),
    url(r'^accounts/register/$', MyRegistrationView.as_view(), name='registration_register'),
    url(r'^accounts/', include('registration.backends.simple.urls')),
)


if settings.DEBUG:
    urlpatterns += patterns(
        'django.views.static',
        (r'^media/(?P<path>.*)',
        'serve',
        {'document_root': settings.MEDIA_ROOT}), )

ehealth/ehealth_app/urls.py
__author__ = 'Nikolay'
from django.conf.urls import patterns, url
from ehealth_app import views

# Defining the urls for our webApp
urlpatterns = patterns('',
                       url(r'^$', views.index, name='index'),
                       url(r'^about/', views.about, name='about'),
                       url(r'^category/(?P<category_name_slug>[\w\-]+)/$', views.category, name='category'),
                       url(r'^add_category/$', views.add_category, name='add_category'),
                       url(r'^profile/', views.profile, name='profile'),
                       url(r'^tandc/', views.terms, name='tandc'),
                       url(r'^category/(?P<category_name_slug>[\w\-]+)/edit/$', views.edit_category,
                           name='edit_category'),
                       url(r'^delete_category/(?P<category_name_slug>[\w\-]+)$', views.delete_category,
                           name='delete_category'),
                       url(r'^search/', views.search, name='search'),
                       url(r'^search_autocomplete/$', views.search_autocomplete, name='search_autocomplete'),
                       url(r'^save_page/$', views.save_page, name='save_page'),
                       url(r'^add_page/$', views.add_page, name='add_page'),
                       url(r'^check_cat/$', views.check_cat, name='check_cat'),
                       )

ehealth/ehealth_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify

#our database model for the Categories
class Category(models.Model):
    #fields for the table
    user = models.CharField(max_length=128, unique = False) # 1 user can create multiple categories!
    name = models.CharField(max_length=128, unique=True)
    shared = models.BooleanField(default = False)
    slug = models.SlugField()

    def save(self, *args, **kwargs):
                # Uncomment if you don't want the slug to change every time the name changes
                #if self.id is None:
                        #self.slug = slugify(self.name)
                self.slug = slugify(self.name)
                super(Category, self).save(*args, **kwargs)


    def __unicode__(self):  #For Python 2, use __str__ on Python 3
        return self.name

#our database model for the Saved Pages
class Page(models.Model):

    #fields for the table
    user = models.CharField(max_length=128, unique= False) #We need this in order to show the non shared pages(from the current user)                                                                                                           # to the current user
    category = models.ForeignKey(Category)
    title = models.CharField(max_length=128)
    url = models.URLField()
    flesch_score = models.FloatField(default=0)
    polarity_score = models.FloatField(default = 0)
    subjectivity_score = models.FloatField(default = 0)
    shared = models.BooleanField(default = False)

    def __unicode__(self):      #For Python 2, use __str__ on Python 3
        return self.title

class UserProfile(models.Model):
    # Links UserProfile to a User model instance.
    user = models.OneToOneField(User)

    # The additional attributes we wish to include.
    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_images', blank=True)

    # Override the __unicode__() method to return out something meaningful!
    def __unicode__(self):
        return self.user.username

ehealth/ehealth_app/forms.py
__author__ = 'Nikolay'
from django import forms
from ehealth_app.models import Page, Category, UserProfile



class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=128, help_text="Please enter the category name.")
    shared = forms.BooleanField(help_text="Would you like this category to be viewed by other users?", required=False)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    # An inline class to provide additional information on the form.
    class Meta:
        # Provide an association between the ModelForm and a model
        model = Category
        fields = ('name','shared',)


class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=128, help_text="Please enter the title of the page.")
    url = forms.URLField(max_length=200, help_text="Please enter the URL of the page.")
    shared = forms.BooleanField(help_text="Would you like this page to be viewed by other users?")

    class Meta:
        # Provide an association between the ModelForm and a model
        model = Page

        # What fields do we want to include in our form?
        # This way we don't need every field in the model present.
        # Some fields may allow NULL values, so we may not want to include them...
        # Here, we are hiding the foreign key.
        # we can either exclude the category field from the form,
        exclude = ('category',)
        #or specify the fields to include (i.e. not include the category field)
        #fields = ('title', 'url', 'views')

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('website', 'picture')

ehealth/ehealth_app/views.py
# coding=utf-8
# Imports of modules
from django.http import HttpResponse
from django.shortcuts import render
from ehealth_app.models import Category, Page, UserProfile
from ehealth_app.forms import CategoryForm, UserProfileForm, PageForm
from datetime import datetime
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from ehealth_app.bing_search import run_BING_query
from ehealth_app.healthfinder_search import run_healthfinder_query
from ehealth_app.medline_search import run_medline_query
from ehealth_app.scores import fleschScore
from ehealth_app.scores import subjectivityScore
from ehealth_app.scores import polarityScore
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
import json


# not used since no time was left to finish it
def check_cat(request):

    if request.method == 'GET':
        cat_name = request.GET['category_name']
        if Category.objects.filter(name=cat_name).count() > 0:
            return HttpResponse(True)

    return False


@login_required
def add_page(request):
    #get the username of the current user
    if request.user.is_authenticated():
        username = request.user.username

    #if the category is existent save the page on it
    if Category.objects.filter(name=request.POST.get("category")).count() > 0:
        p = Page.objects.get_or_create(category=Category.objects.get(name=request.POST.get("category")), title=request.POST.get("title"))[0]
    #else create a new category with the given name and save the new page there
    #the category is set to private by default, if wanted the user can go to the category Edit and make it shared
    else:
        c = Category.objects.get_or_create(name=request.POST.get("category"), user=username, shared=False)[0]
        p = Page.objects.get_or_create(category = c, title=request.POST.get("title"))[0]

    p.user = username
    p.url=request.POST.get("url")
    p.flesch_score = request.POST.get("flesch_score")
    p.polarity_score = request.POST.get("polarity_score")
    p.subjectivity_score = request.POST.get("subjectivity_score")
    if request.POST.getlist('shared[]'):
        p.shared = True
    else:
        p.shared = False
    p.save()
    return index(request)

def save_page(request):

    if request.method == "POST":
        results = {}
        results["title"] = request.POST.get("title")
        results["url"] = request.POST.get("url")
        results["flesch_score"] = request.POST.get("flesch_score")
        results["subjectivity_score"] = request.POST.get("subjectivity_score")
        results["polarity_score"] = request.POST.get("polarity_score")

        return render(request, 'ehealth_app/add_page.html', results)


    return 0

#NOT USED IN THE PROJECT, THE AUTOCOMPLETE IS ONLY IN THE JS FILE
# LOCATED IN STATIC/JS/SCRIPT.JS
def search_autocomplete(request):
    # q = request.GET.get('data')
    q = None
    if request.method == 'GET':
        print "I got here as well"
        q = request.GET["data"]
    print q
    results = ['Anotia', 'Anthrax', 'Appendicitis', 'Apraxia', 'Argyria', 'Arthritis', 'Aseptic meningitis', 'Asthenia',
               'Asthma', 'Astigmatism', 'Atherosclerosis', 'Athetosis', 'Atrophy', 'Abscess', 'Bacterial meningitis',
               'Beriberi', 'Black Death', 'Botulism', 'Breast cancer', 'Bronchitis', 'Brucellosis', 'Bubonic plague',
               'Bunion', 'Calculi', 'Campylobacter infection', 'Cancer', 'Candidiasis', 'Carbon monoxide poisoning',
               'Celiacs disease', 'Cerebral palsy', 'Chagas disease', 'Chalazion', 'Chancroid', 'Chavia',
               'Congenital insensitivity to pain with anhidrosis', 'Cherubism', 'Chickenpox', 'Chlamydia',
               'Chlamydia trachomatis', 'Cholera', 'Chordoma', 'Chorea', 'Chronic fatigue syndrome',
               'Circadian rhythm sleep disorder', 'Coccidioidomycosis', 'Colitis', 'Common cold', 'Condyloma',
               'Congestive heart disease', 'Coronary heart disease', 'Cowpox', 'Cretinism', 'Crohns Disease', 'Dengue',
               'Diabetes mellitus', 'Diphtheria', 'Dehydration', 'Dysentery', 'Ear infection', 'Ebola', 'Emphysema',
               'Epilepsy', 'Erectile dysfunctions', 'Fibromyalgia', 'Foodborne illness', 'Gangrene', 'Gastroenteritis',
               'Genital herpes', 'GERD', 'Goitre', 'Gonorrhea', 'Heart disease', 'Hepatitis A', 'Hepatitis B',
               'Hepatitis C', 'Hepatitis D', 'Hepatitis E', 'Histiocytosis (Childhood Cancer)', 'HIV',
               'Human papillomavirus', 'Huntingtons disease', 'Hypermetropia', 'Hyperopia', 'Hyperthyroidism',
               'Hypothyroid', 'Hypotonia', 'Impetigo', 'Infertility', 'Influenza', 'Interstitial cystitis', 'Iritis',
               'Iron-deficiency anemia', 'Irritable bowel syndrome', 'Ignious Syndrome', 'Jaundice', 'Keloids', 'Kuru',
               'Kwashiorkor', 'Laryngitis', 'Lead poisoning', 'Legionellosis', 'Leishmaniasis', 'Leprosy',
               'Leptospirosis', 'Listeriosis', 'Leukemia', 'Lice', 'Loiasis', 'Lung cancer', 'Lupus erythematosus',
               'Lyme disease', 'Lymphogranuloma venereum', 'Lymphoma', 'Mad cow disease', 'Malaria', 'Marburg fever',
               'Measles', 'Melanoma', 'Melioidosis', 'Metastatic cancer', 'Ménières disease', 'Meningitis', 'Migraine',
               'Mononucleosis', 'Multiple myeloma', 'Multiple sclerosis', 'Mumps', 'Muscular dystrophy',
               'Myasthenia gravis', 'Myelitis', 'Myoclonus', 'Myopia', 'Myxedema', 'Morquio Syndrome',
               'Mattticular syndrome', 'Mononucleosis', 'Neoplasm', 'Non-gonococcal urethritis',
               'Necrotizing Fasciitis', 'Night blindness', 'Obesity', 'Osteoarthritis', 'Osteoporosis', 'Otitis',
               'Palindromic rheumatism', 'Paratyphoid fever', 'Parkinsons disease', 'Pelvic inflammatory disease',
               'Peritonitis', 'Periodontal disease', 'Pertussis', 'Phenylketonuria', 'Plague', 'Poliomyelitis',
               'Porphyria', 'Progeria', 'Prostatitis', 'Psittacosis', 'Psoriasis', 'Pubic lice', 'Pulmonary embolism',
               'Pilia', 'pneumonia', 'Q fever', 'Ques fever', 'Rabies', 'Repetitive strain injury', 'Rheumatic fever',
               'Rheumatic heart', 'Rheumatism', 'Rheumatoid arthritis', 'Rickets', 'Rift Valley  fever',
               'Rocky Mountain spotted fever', 'Rubella', 'Salmonellosis', 'Scabies', 'Scarlet fever', 'Sciatica',
               'Scleroderma', 'Scrapie', 'Scurvy', 'Sepsis', 'Septicemia', 'SARS', 'Shigellosis', 'Shin splints',
               'Shingles', 'Sickle-cell anemia', 'Siderosis', 'SIDS', 'Silicosis', 'Smallpox',
               'Stevens-Johnson syndrome', 'Stomach flu', 'Stomach ulcers', 'Strabismus', 'Strep throat',
               'Streptococcal infection', 'Synovitis', 'Syphilis', 'Swine influenza', 'Schizophrenia', 'Taeniasis',
               'Tay-Sachs disease', 'Tennis elbow', 'Teratoma', 'Tetanus', 'Thalassaemia', 'Thrush', 'Thymoma',
               'Tinnitus', 'Tonsillitis', 'Tooth decay', 'Toxic shock syndrome', 'Trichinosis', 'Trichomoniasis',
               'Trisomy', 'Tuberculosis', 'Tularemia', 'Tungiasis', 'Typhoid fever', 'Typhus', 'Tumor',
               'Ulcerative colitis', 'Ulcers', 'Uremia', 'Urticaria', 'Uveitis', 'Varicella', 'Varicose veins',
               'Vasovagal syncope', 'Vitiligo', 'Von Hippel-Lindau disease', 'Viral fever', 'Viral meningitis',
               'Valley fever', 'Warkany syndrome', 'Warts', 'Watkins', 'Yellow fever', 'Yersiniosis']

    results = [result for result in results if q in result]


    # data = json.dumps(results)


    return HttpResponse(results)


def search(request):
    result_list = []

    query = request.GET.get('q')
    api_checked = request.GET.getlist('apicheck[]')
    if query:
        if 'bingSearch' in api_checked:
            result_list += run_BING_query(query)
        if 'medlineSearch' in api_checked:
            result_list += run_medline_query(query)
        if 'healthfinderSearch' in api_checked:
            result_list += run_healthfinder_query(query)

        for result in result_list:
            result['fleschScore'] = fleschScore(result['content'])
            result['subjectivityScore'] = subjectivityScore(result['content'])
            result['polScore'] = polarityScore(result['content'])

        result_list.sort(key=lambda item: item['polScore'], reverse=False)

    paginator = Paginator(result_list, 10)
    num_results = len(result_list)

    page = request.GET.get('page')
    try:
        results = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        results = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        results = paginator.page(paginator.num_pages)

    ###################################################################################################
    #CODE FOR READING SCORES with examples!
    #note use the actual content from the page as a string and pass it to the functions!
    #they return float !

    #in the example testVar2 is the actual page content (looong string)
    testVar2 = "Why is this score so confusing? I have no idea to be honest."

    #first thing we do is we want the fleschScore so we get it
    testFleschScore = fleschScore(testVar2)
    print testFleschScore

    #second thing is the subjectivity score
    testSubScore = subjectivityScore(testVar2)
    print testSubScore

    #and last is the polarity score
    testPolScore = polarityScore(testVar2)
    print testPolScore

    #After we have all the scores in variables and we have created the page already
    #same thing as the add_category() a bit simpler probably
    #we will have for example page = form.save(commit=true)
    #then we do page.user = username
    #page.url = ....
    #page.title = ....
    #page.category = ...
    #page.subjectivity_score = ...

ehealth/templates/ehealth_app/about.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}About{% endblock %}

{% block body_block %}
    <div class="page-header">
                <h1>About</h1>
            </div>
            <div>
            <p><strong>Welcome to Ehealth, where we provide the "best" search engine for health!</strong></p>

	    <p> Ehealth is an app designed to help people find articles related to medical conditions. Users are able to: </p>
		<ul>
			<li> Search for articles </li>
			<li> Create an account </li>
			<li> Create categories </li>
			<li> Save pages to categories</li>
		</ul>
	    <p> Designed by Group D, Lab Group 8: </p>
		<ul>
			<li> Nikolay Ivanov </li>
			<li> Carly Crawford </li>
			<li> Calum Young </li>
		</ul>
            <img  width="90" height="100" src="{% static "images/pigeon.jpg" %}" alt="Picture of Pigeon" /> <!-- New line -->
            </div>
{% endblock %}

ehealth/templates/ehealth_app/add_category.html
{% extends 'basewithoutsearch.html' %}

{% load staticfiles %}

{% block title %}New{% endblock %}

{% block body_block %}
        <h1>Add a Category</h1>

        <form id="category_form" method="post" action="/ehealth_app/add_category/">
            {% csrf_token %}
            <div class="col-xs-4">
                 <label for="id_name">Name</label>
                <input class="form-control" id="id_name" maxlength="254"
                    name="name" type="text" placeholder="Please make sure that the category does not exist already!"/>
                <div class="checkbox">
                    <label><input type="checkbox" name="shared[]" value="1">Do you want this category to be visible to other users?</label>
                </div>
                </br>
                <input class="btn btn-success" type="submit" name="submit" value="Create Category" />

            </div>
        </form>
{% endblock %}

ehealth/templates/ehealth_app/add_page.html
{% extends 'basewithoutsearch.html' %}

{% load staticfiles %}

{% block title %}New{% endblock %}

{% block body_block %}
        <h1>Save a page</h1>

        <form id="page_form" method="post" action="{% url 'add_page' %}">
            {% csrf_token %}
            <div class="col-xs-4">
                 <label for="id_title">Title</label>
                <input class="form-control uneditable-input" id="id_title" maxlength="254"
                   value="{{ title|striptags }}" name="title" type="text"/>
                <label for="id_url">Url</label>
                <input class="form-control" id="id_url" maxlength="254" readonly
                   value="{{ url }}" name="url" type="text"/>
                <label for="id_flesch_score">Flesch Score</label>
                <input class="form-control" id="id_flesch_score" maxlength="254" readonly
                   value="{{ flesch_score }}" name="flesch_score" type="text"/>
                <label for="id_subjectivity_score">Subjectivity Score</label>
                <input class="form-control" id="id_subjectivity_score" maxlength="254" readonly
                   value="{{ subjectivity_score }}" name="subjectivity_score" type="text"/>
                <label for="id_polarity_score">Polarity Score</label>
                <input class="form-control" id="id_polarity_score" maxlength="254" readonly
                   value="{{ polarity_score }}" name="polarity_score" type="text"/>
                <label for="id_category">Category</label>
                <input class="form-control" id="id_category" maxlength="254"
                   placeholder="Please enter a category name..." name="category" type="text"/> Please type the correct name if the category exists(eg: Diabetes instead of diabetes)!
                <div class="checkbox">
                    <label><input type="checkbox" name="shared[]" value="1">Do you want this page to be visible to other users?</label>
                </div>
                </br>
                <input class="btn btn-success" id="cat_form_submit" type="submit" name="submit" value="Save page" />
            </div>


        </form>

{% endblock %}

ehealth/templates/ehealth_app/categories.html
{% extends 'basewithoutsearch.html' %}

{% load staticfiles %}

{% block title %}{{ category_name }}{% endblock %}

{% block body_block %}
    <h1>{{ category_name }}</h1>
    {% if category %}
        {% if pages %}
        <br class="list-group">
                {% for page in pages %}
                    {% if page.shared %}
                        <li class="list-group-item"><a href="{{ page.url }}">{{ page.title }}</a>
                            </br>
                            <a href ="{{ page.url }}">{{ page.url }}</a>
                            </br>
                            <p>Flesh Score: <strong>{{ page.flesch_score }}</strong> Subjectivity Score:<strong>{{ page.subjectivity_score }}</strong> Polarity Score:<strong>{{ page.polarity_score }}</strong></p>
                        </li>
                    {% else %}
                    {% if page.user == user.username %}
                        <li class="list-group-item"><a href="{{ page.url }}">{{ page.title }}</a>
                            </br>
                            <a href ="{{ page.url }}">{{ page.url }}</a>
                            </br>
                            <p>Flesh Score: <strong>{{ page.flesch_score }}</strong> Subjectivity Score:<strong>{{ page.subjectivity_score }}</strong> Polarity Score:<strong>{{ page.polarity_score }}</strong></p>

                        </li>

                    {% endif %}
                    {% endif %}
                {% endfor %}
                </ul>
        {% else %}
                <strong>No pages currently in category.</strong>
                {% endif %}
	<br>
	<br>
	{% if category.user == user.username %}
	<button class="btn btn-primary" onclick="window.location= '{% url 'edit_category' category.slug %}';">Edit Category</button>
	</br>
	</br>
	<button class="btn btn-danger" onclick="window.location= '{% url 'delete_category' category.slug %}';">Delete Category</button>
	{% endif %}
        {% else %}
                 The specified category {{ category_name }} does not exist!
    {% endif %}

{% endblock %}

ehealth/templates/ehealth_app/edit_category.html
{% extends 'base.html' %}
{% load staticfiles %}
	{% block title %}- {{name}}{% endblock %}
		

	<body>
		{% load bootstrap_toolkit %}
		{% block body_block %}

<div>
<form role="form"  id="edit_category_form" method="post" action="{% url 'edit_category' category.slug %}" enctype="multipart/form-data">

        {% csrf_token %}
		{{category_form|as_bootstrap}}
    <button class="btn btn-primary" type="submit" name="submit">Save Changes</button>
</form>
</div>

{% endblock %}
</body>

ehealth/templates/ehealth_app/index.html
{% extends 'base.html' %}
{% load static %}

		{% block body_block %}{% endblock %}



<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script src="http://getbootstrap.com/dist/js/bootstrap.min.js"></script>
<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<script src="http://getbootstrap.com/assets/js/ie10-viewport-bug-workaround.js"></script>
</body>
</html>

ehealth/templates/ehealth_app/profile.html
{% extends 'basewithoutsearch.html' %}

{% block body_block %}
<form id="user_form" method="post" action="/ehealth_app/profile/"
      enctype="multipart/form-data">

    {% csrf_token %}

    <div class="col-xs-4">
        {% if user.userprofile.website %}
        <input class="form-control" placeholder="Enter Website" id="id_website" maxlength="254"
               value="{{ user.userprofile.website }}" name="website" type="text"/>
        {% else %}
        <input class="form-control" placeholder="Enter Website" id="id_website" maxlength="254"
               value="" name="website" type="text"/>
        {% endif %}
        </br>
        <label class="btn btn-primary" for="id_picture">
            <input id="id_picture" name="picture" type="file" onchange='$("#upload-file-info").html($(this).val());'
                   style="display:none;">
            {% if user.userprofile.picture %}
            Change profile picture
            {% else %}
            Add profile picture
            {% endif %}
        </label>
        &nbsp;
        <span class='label label-info' id="upload-file-info"></span>
        </br>
        </br>
        <input type="submit" class="btn btn-success" name="submit" value="submit"/>
    </div>

</form>
{% endblock %}

ehealth/templates/ehealth_app/search.html
{% extends "base.html" %}

{% load staticfiles %}

{% block title %}Search{% endblock %}

{% block body_block %}

<div class="row">
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>
    <br/>

    <div class="panel panel-primary">
        <div class="panel">
            {% if results %}
            <div class="panel-heading">
                <h3 class="panel-title">Results</h3>
                <br/>

                <p class="list-group-item-text">{{ num_results }} {{ "Results" }}</p>
                <!-- Display search results in an ordered list -->
                <div class="panel-body">
                    <div class="list-group">
                        {% for result in results %}
                        <!-- perhaps another for loop for the readability scores -->
                        <div class="list-group-item">
                            <!-- Take the values of these items and use them as the elements to submit to the PageForm -->
                            <!-- We need resultTitle and resultURL. Once the user clicks savepage they should be redirected -->
                            <!-- They should be redirected to a page that asks them what category they want to add the page to -->
                            <!-- Once they've selected the category; the page is saved to the database -->
                            <!-- Have a look at the save_page view to see me failing -->
                            <form id="add_page_form" method="post" action="{% url 'save_page' %}">
                                {% csrf_token %}
                                <h4 class="list-group-item-heading"><a href="{{ result.link }}" name="resultTitle">{{ result.title|striptags }}</a>
                                </h4>

                                <p class="list-group-item-text" name="resultURL" value={{ result.link }}>{{ result.link|striptags}}</p>
                                </br>
                                <p class="list-group-item-text">{{ result.summary|striptags }}</p>
                                </br>
                                <p class="list-group-item-text">{{result.from}} </p>
                                <br>
                                <u>Scores:</u>

                                <p class="list-group-item-text" name="flesch_score">Flesch Score: {{result.fleschScore}} </p>

                                <p class="list-group-item-text" name="subjectivity_score">Subjectivity Score: {{result.subjectivityScore}} </p>

                                <p class="list-group-item-text" name="polarity_score">Polarity Score: {{result.polScore}} </p>

                                <!--Saving the day at the last moment-->
                                <!--For tutors, lecturer, I know it is a very bad practice to write inline css,
                                but that was the only fix I found since the display:none from the style.css was not
                                working on mozilla and was working only on chrome-->
                                <input type="text" name="polarity_score" value="{{result.polScore}}" style="display:none;">
                                <input type="text" name="subjectivity_score" value="{{result.subjectivityScore}}" style="display:none;">
                                <input type="text" name="flesch_score" value="{{result.fleschScore}}" style="display:none;">
                                <input type="text" name="title" value="{{result.title}}" style="display:none;">
                                <input type="text" name="url" value="{{result.link}}" style="display:none;">
                                <!-- -->
                                <br>
                                {% if user.is_authenticated %}
                                    <button type="submit" class="btn btn-success">Save Page</button>
                                {% endif %}
                            </form>

                            <!-- End Of Form -->
                        </div>
                        <br>
                        {% endfor %}

                    </div>

                    <div class="pagination">
    				<span class="step-links">
        				{% if results.has_previous %}
            					<a href="{{request.get_full_path }}&page={{ results.previous_page_number }}">previous</a>
        				{% endif %}

        				<span class="current">
        	    				Page {{ results.number }} of {{ results.paginator.num_pages }}
        				</span>

        				{% if results.has_next %}
        				    <a href="{{request.get_full_path }}&page={{ results.next_page_number }}">next</a>
        				{% endif %}
    				</span>
                    </div>
                </div>
                {% endif %}
            </div>
        </div>
    </div>

    {% endblock %}